### ISSUE TITLE
Java class "jp.ngt.rtm.entity.EntityTrainDetector" has no public instance field or method named "class"

### ISSUE THREAD

**Issue by anatawa12** [anatawa12/fixRTM#84]
fixRTM: 2.0.7

pack: https://twitter.com/hi03_s/status/1244004412021825537

```
[18:02:17] [Server thread/WARN] []: org.mozilla.javascript.EvaluatorException: Java class "jp.ngt.rtm.entity.EntityTrainDetector" has no public instance field or method named "class". (minecraft:scripts/serverd_rsdel.js#18)
[18:02:17] [Server thread/WARN] []: 	at org.mozilla.javascript.DefaultErrorReporter.runtimeError(DefaultErrorReporter.java:79)
[18:02:17] [Server thread/WARN] []: 	at org.mozilla.javascript.Context.reportRuntimeError(Context.java:1011)
[18:02:17] [Server thread/WARN] []: 	at org.mozilla.javascript.Context.reportRuntimeError(Context.java:1064)
[18:02:17] [Server thread/WARN] []: 	at org.mozilla.javascript.Context.reportRuntimeError2(Context.java:1034)
[18:02:17] [Server thread/WARN] []: 	at org.mozilla.javascript.JavaMembers.reportMemberNotFound(JavaMembers.java:855)
[18:02:17] [Server thread/WARN] []: 	at org.mozilla.javascript.NativeJavaClass.get(NativeJavaClass.java:102)
[18:02:17] [Server thread/WARN] []: 	at org.mozilla.javascript.ScriptableObject.getProperty(ScriptableObject.java:2320)
[18:02:17] [Server thread/WARN] []: 	at org.mozilla.javascript.ScriptRuntime.getObjectProp(ScriptRuntime.java:1578)
[18:02:17] [Server thread/WARN] []: 	at org.mozilla.javascript.ScriptRuntime.getObjectProp(ScriptRuntime.java:1571)
[18:02:17] [Server thread/WARN] []: 	at com.anatawa12.fixRtm.scripting.compiled.c_13d699a7b36f5c1cae1b977596cd01b9b622dcae._c_onUpdate_1(minecraft:scripts/serverd_rsdel.js:18)
[18:02:17] [Server thread/WARN] []: 	at com.anatawa12.fixRtm.scripting.compiled.c_13d699a7b36f5c1cae1b977596cd01b9b622dcae.call(minecraft:scripts/serverd_rsdel.js)
[18:02:17] [Server thread/WARN] []: 	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
[18:02:17] [Server thread/WARN] []: 	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3545)
[18:02:17] [Server thread/WARN] []: 	at com.anatawa12.fixRtm.scripting.compiled.c_13d699a7b36f5c1cae1b977596cd01b9b622dcae.call(minecraft:scripts/serverd_rsdel.js)
[18:02:17] [Server thread/WARN] []: 	at com.anatawa12.fixRtm.scripting.FIXScriptEngine.invokeFunction(FIXScriptEngine.kt:75)
[18:02:17] [Server thread/WARN] []: 	at jp.ngt.ngtlib.io.ScriptUtil.doScriptFunction(ScriptUtil.java:116)
[18:02:17] [Server thread/WARN] []: 	at jp.ngt.ngtlib.io.ScriptUtil.doScriptIgnoreError(ScriptUtil.java:132)
[18:02:17] [Server thread/WARN] []: 	at jp.ngt.rtm.modelpack.ScriptExecuter.callMethod(ScriptExecuter.java:30)
[18:02:17] [Server thread/WARN] []: 	at jp.ngt.rtm.modelpack.ScriptExecuter.execScript(ScriptExecuter.java:38)
[18:02:17] [Server thread/WARN] []: 	at jp.ngt.rtm.entity.EntityInstalledObject.func_70071_h_(EntityInstalledObject.java:98)
[18:02:17] [Server thread/WARN] []: 	at jp.ngt.rtm.entity.EntityElectricalWiring.func_70071_h_(EntityElectricalWiring.java:39)
[18:02:17] [Server thread/WARN] []: 	at jp.ngt.rtm.entity.EntityTrainDetector.func_70071_h_(EntityTrainDetector.java:62)
[18:02:17] [Server thread/WARN] []: 	at net.minecraft.world.World.func_72866_a(World.java:2406)
[18:02:17] [Server thread/WARN] []: 	at net.minecraft.world.World.func_72870_g(World.java:2357)
[18:02:17] [Server thread/WARN] []: 	at net.minecraft.world.World.func_72939_s(World.java:2129)
[18:02:17] [Server thread/WARN] []: 	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:712)
[18:02:17] [Server thread/WARN] []: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:901)
[18:02:17] [Server thread/WARN] []: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:466)
[18:02:17] [Server thread/WARN] []: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:779)
[18:02:17] [Server thread/WARN] []: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:625)
[18:02:17] [Server thread/WARN] []: 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by anatawa12** [comment]
[hi03TrainDetector1.0-1.12.2-debug.bsdiff.zip](https://github.com/anatawa12/fixRTM/files/4676018/hi03TrainDetector1.0-1.12.2-debug.bsdiff.zip)

patch to support 1.12.2 and debug env.
